# SPDX-FileCopyrightText: 2023 Sarah Vaupel <sarah.vaupel@uniworx.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

nix:
  enable: true
  shell-file: ./shell.nix

packages:
  - haskell-nf

extra-deps: []

resolver: lts-20.24
